# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get install r-cran-rgl
  - sudo apt-get install libfreetype6-dev 
  - sudo apt-get install libftgl-dev
  - sudo apt-get install mesa-common-dev 
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install ghostscript

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'