# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'