# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

matrix:
  include:
    - os: linux
    - os: osx

r_build_args: "--no-build-vignettes"

r_packages:
  - covr
  - rgl

after_success:
  - Rscript -e 'covr::codecov()'