# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

matrix:
  include:
    - os: linux
    - os: osx

r_packages:
  - covr
  - rgl

after_success:
  - Rscript -e 'covr::codecov()'